name: wntr
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.6
    - numpy
    - scipy
    - networkx
    - pandas
    - matplotlib
    - plotly
    - folium
    - utm
    - sphinx
    - numpydoc